pub mod pe;
pub mod nt;
mod spf;
pub mod utils;
pub mod driver_map;
pub mod traits;
mod convert;
mod ldr;
pub mod translator;
pub mod service;
pub mod exploit;
pub mod provider;
pub mod kernel_call;
pub mod native_buffer;
pub mod kernel_buffer;
pub mod mapped_buffer;